set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)
set(UNITY_PROJECT_PATH ${PROJECT_SOURCE_DIR}/../..)
set(CUSTOM_LIBS_PATH ${PROJECT_SOURCE_DIR}/libs)
set(CSHARP_FRAMEWORK "v4.7.1")
set(WINDOWS_EDITOR_DEFINE "UNITY_2022_1_24;UNITY_2022_1;UNITY_2022;UNITY_5_3_OR_NEWER;UNITY_5_4_OR_NEWER;UNITY_5_5_OR_NEWER;UNITY_5_6_OR_NEWER;UNITY_2017_1_OR_NEWER;UNITY_2017_2_OR_NEWER;UNITY_2017_3_OR_NEWER;UNITY_2017_4_OR_NEWER;UNITY_2018_1_OR_NEWER;UNITY_2018_2_OR_NEWER;UNITY_2018_3_OR_NEWER;UNITY_2018_4_OR_NEWER;UNITY_2019_1_OR_NEWER;UNITY_2019_2_OR_NEWER;UNITY_2019_3_OR_NEWER;UNITY_2019_4_OR_NEWER;UNITY_2020_1_OR_NEWER;UNITY_2020_2_OR_NEWER;UNITY_2020_3_OR_NEWER;UNITY_2021_1_OR_NEWER;UNITY_2021_2_OR_NEWER;UNITY_2021_3_OR_NEWER;UNITY_2022_1_OR_NEWER;UNITY_INCLUDE_TESTS;USE_SEARCH_ENGINE_API;USE_SEARCH_TABLE;USE_SEARCH_MODULE;USE_PROPERTY_DATABASE;USE_QUERY_BUILDER;USE_SEARCH_EXTENSION_API;SCENE_TEMPLATE_MODULE;ENABLE_AR;ENABLE_AUDIO;ENABLE_CACHING;ENABLE_CLOTH;ENABLE_EVENT_QUEUE;ENABLE_MICROPHONE;ENABLE_MULTIPLE_DISPLAYS;ENABLE_PHYSICS;ENABLE_TEXTURE_STREAMING;ENABLE_UNET;ENABLE_LZMA;ENABLE_UNITYEVENTS;ENABLE_VR;ENABLE_WEBCAM;ENABLE_UNITYWEBREQUEST;ENABLE_WWW;ENABLE_CLOUD_SERVICES;ENABLE_CLOUD_SERVICES_COLLAB;ENABLE_CLOUD_SERVICES_COLLAB_SOFTLOCKS;ENABLE_CLOUD_SERVICES_ADS;ENABLE_CLOUD_SERVICES_USE_WEBREQUEST;ENABLE_CLOUD_SERVICES_CRASH_REPORTING;ENABLE_CLOUD_SERVICES_NATIVE_CRASH_REPORTING;ENABLE_CLOUD_SERVICES_PURCHASING;ENABLE_CLOUD_SERVICES_ANALYTICS;ENABLE_CLOUD_SERVICES_UNET;ENABLE_CLOUD_SERVICES_BUILD;ENABLE_EDITOR_GAME_SERVICES;ENABLE_CLOUD_LICENSE;ENABLE_EDITOR_HUB_LICENSE;ENABLE_WEBSOCKET_CLIENT;ENABLE_DIRECTOR_AUDIO;ENABLE_DIRECTOR_TEXTURE;ENABLE_MANAGED_JOBS;ENABLE_MANAGED_TRANSFORM_JOBS;ENABLE_MANAGED_ANIMATION_JOBS;ENABLE_MANAGED_AUDIO_JOBS;ENABLE_RUNTIME_PERMISSIONS;ENABLE_ENGINE_CODE_STRIPPING;ENABLE_ONSCREEN_KEYBOARD;ENABLE_MANAGED_UNITYTLS;INCLUDE_DYNAMIC_GI;ENABLE_SCRIPTING_GC_WBARRIERS;PLATFORM_SUPPORTS_MONO;ENABLE_VIDEO;ENABLE_ACCELERATOR_CLIENT_DEBUGGING;PLATFORM_ANDROID;TEXTCORE_1_0_OR_NEWER;UNITY_ANDROID;UNITY_ANDROID_API;ENABLE_EGL;ENABLE_NETWORK;ENABLE_RUNTIME_GI;ENABLE_CRUNCH_TEXTURE_COMPRESSION;UNITY_CAN_SHOW_SPLASH_SCREEN;UNITY_HAS_GOOGLEVR;UNITY_HAS_TANGO;ENABLE_SPATIALTRACKING;ENABLE_ETC_COMPRESSION;PLATFORM_EXTENDS_VULKAN_DEVICE;PLATFORM_HAS_MULTIPLE_SWAPCHAINS;UNITY_ANDROID_SUPPORTS_SHADOWFILES;PLATFORM_UPDATES_TIME_OUTSIDE_OF_PLAYER_LOOP;ENABLE_UNITYADS_RUNTIME;UNITY_UNITYADS_API;ENABLE_MONO;NET_STANDARD_2_0;NET_STANDARD;NET_STANDARD_2_1;NETSTANDARD;NETSTANDARD2_1;ENABLE_PROFILER;DEBUG;TRACE;UNITY_ASSERTIONS;UNITY_EDITOR;UNITY_EDITOR_64;UNITY_EDITOR_WIN;ENABLE_UNITY_COLLECTIONS_CHECKS;ENABLE_BURST_AOT;UNITY_TEAM_LICENSE;UNITY_PRO_LICENSE;ENABLE_CUSTOM_RENDER_TEXTURE;ENABLE_DIRECTOR;ENABLE_LOCALIZATION;ENABLE_SPRITES;ENABLE_TERRAIN;ENABLE_TILEMAP;ENABLE_TIMELINE;ENABLE_LEGACY_INPUT_MANAGER;AMLOG_ON;YHLOG_ON;YHLOG_ERROR_ON;CSHARP_7_OR_LATER;CSHARP_7_3_OR_NEWER")


file(GLOB_RECURSE CUSTOM_LIB_DLLS
    ${CUSTOM_LIBS_PATH}/*.dll
)
set(CUSTOM_LIB_DLLS_RUNTIME ${CUSTOM_LIB_DLLS})
list(FILTER CUSTOM_LIB_DLLS_RUNTIME EXCLUDE REGEX ".*Editor.*")
# message(STATUS ${CUSTOM_LIB_DLLS})
# message(STATUS ${CUSTOM_LIB_DLLS_RUNTIME})

file(GLOB_RECURSE CUSTOM_LIB_DLLS_EDITOR
    ${CUSTOM_LIBS_PATH}/*.Editor.dll
)
# message(STATUS ${CUSTOM_LIB_DLLS_EDITOR})

file(GLOB ASSET_ROOT_DLLS
    ${UNITY_PROJECT_PATH}/Assets/*.dll
)
#message(STATUS ${ASSET_ROOT_DLLS})

file(GLOB_RECURSE PLUGIN_DLLS
    ${UNITY_PROJECT_PATH}/Assets/Plugins/*.dll
)
#list(FILTER PLUGIN_DLLS EXCLUDE REGEX ".*/Editor/.*")
#message(STATUS ${PLUGIN_DLLS})

file(GLOB_RECURSE EDITOR_DLLS
    ${UNITY_PROJECT_PATH}/Assets/Editor/*.dll
    ${UNITY_PROJECT_PATH}/Assets/Plugins/*.dll
)
list(FILTER EDITOR_DLLS INCLUDE REGEX ".*/Editor/.*")

#message(STATUS ${PLUGIN_DLLS})

set(COMMON_DOTNET_REFERENCES "Microsoft.CSharp"
    "PresentationCore"
    "PresentationFramework"
    "System"
    "System.Core"
    "System.Data"
    "System.Data.DataSetExtensions"
    "System.Net"
    "System.Net.Http"
    "System.Xaml"
    "System.Xml"
    "System.Xml.Linq"
    "System.Runtime.Serialization"
)


function(set_charp_defines)
    foreach(_define IN ITEMS ${ARGN})
        SET(_CSharp_FLAGS "${_CSharp_FLAGS} /define:${_define}")
    endforeach()
    SET(CMAKE_CSharp_FLAGS "${CMAKE_CSharp_FLAGS} ${_CSharp_FLAGS}" PARENT_SCOPE)
endfunction()


function(assign_source_group)
    foreach(_source IN ITEMS ${ARGN})
        if (IS_ABSOLUTE "${_source}")
            file(RELATIVE_PATH _source_rel "${UNITY_PROJECT_PATH}" "${_source}")
        else()
            set(_source_rel "${_source}")
        endif()
        get_filename_component(_source_path "${_source_rel}" PATH)
        string(REPLACE "/" "\\" _source_path_msvc "${_source_path}")
        source_group("${_source_path_msvc}" FILES "${_source}")
    endforeach()
endfunction()