# configuration
set(CONFIGURATION_WIN_STANDALONE_EDITOR "WindowsEditor")
set(CONFIGURATION_WIN_STANDALONE_RUNTIME "WindowsRuntime")
set(CONFIGURATION_WIN_ANDROID_EDITOR "AndroidEditor")
set(CONFIGURATION_WIN_ANDROID_RUNTIME "AndroidRuntime")
set(CONFIGURATION_MAC_IOS_EDITOR "IosEditor")
set(CONFIGURATION_MAC_IOS_RUNTIME "IosRuntime")

if(NOT SET_UP_CONFIGURATIONS_DONE)
    set(SET_UP_CONFIGURATIONS_DONE TRUE)

    # No reason to set CMAKE_CONFIGURATION_TYPES if it's not a multiconfig generator
    # Also no reason mess with CMAKE_BUILD_TYPE if it's a multiconfig generator.
    get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(isMultiConfig)
        message("support multi config.")
        set(CMAKE_CONFIGURATION_TYPES "Debug;Release" CACHE STRING "" FORCE)
        set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES};${CONFIGURATION_WIN_STANDALONE_EDITOR}" CACHE STRING "" FORCE)
        set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES};${CONFIGURATION_WIN_STANDALONE_RUNTIME}" CACHE STRING "" FORCE)
        set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES};${CONFIGURATION_WIN_ANDROID_EDITOR}" CACHE STRING "" FORCE)
        set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES};${CONFIGURATION_WIN_ANDROID_RUNTIME}" CACHE STRING "" FORCE)
        set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES};${CONFIGURATION_MAC_IOS_EDITOR}" CACHE STRING "" FORCE)
        set(CMAKE_CONFIGURATION_TYPES "${CMAKE_CONFIGURATION_TYPES};${CONFIGURATION_MAC_IOS_RUNTIME}" CACHE STRING "" FORCE)
    else()
        message("only single config.")
        if(NOT CMAKE_BUILD_TYPE)
            message("Defaulting to release build.")
            set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
        endif()
        set_property(CACHE CMAKE_BUILD_TYPE PROPERTY HELPSTRING "Choose the type of build")
        # set the valid options for cmake-gui drop-down list
        set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug;Release;${CONFIGURATION_WIN_STANDALONE_EDITOR};${CONFIGURATION_WIN_STANDALONE_RUNTIME};${CONFIGURATION_WIN_ANDROID_EDITOR};${CONFIGURATION_WIN_ANDROID_RUNTIME};${CONFIGURATION_MAC_IOS_EDITOR};${CONFIGURATION_MAC_IOS_RUNTIME}")
    endif()
    # now set up the Profile configuration
    # set(CMAKE_C_FLAGS_PROFILE "...")
    # set(CMAKE_CXX_FLAGS_PROFILE "...")
    # set(CMAKE_EXE_LINKER_FLAGS_PROFILE "...")
endif()